language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t devnryn/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true devnryn/react-test npm test -- --coverage 
    
after_success:
    - docker build -t devnryn/multi-client ./client
    - docker build -t devnryn/multi-nginx ./nginx
    - docker build -t devnryn/multi-server ./server
    - docker build -t devnryn/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take these images and push them to docker hub 
    - docker push devnryn/multi-client
    - docker push devnryn/multi-nginx
    - docker push devnryn/multi-server
    - docker push devnryn/multi-worker

deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-200065275423    
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY